Changes for PowerAPI monitoring

diff --git a/.github/workflows/verify_api.yml b/.github/workflows/verify_api.yml
--- a/.github/workflows/verify_api.yml
+++ b/.github/workflows/verify_api.yml
@@ -1,36 +1,26 @@
-name: Verify API
-on:
-  push:
-    branches:
-      - main
-      - release-*
-    paths:
-      - 'scripts/*'
-      - 'api-generator/*'
-  pull_request:
-    branches:
-      - main
-      - release-*
-    paths:
-      - 'scripts/**'
-      - 'api-generator/**'
 jobs:
   verify:
-    timeout-minutes: 30
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v2
-      - uses: microsoft/playwright-github-action@v1
-      - name: Download drivers
-        run: scripts/download_driver_for_all_platforms.sh
-      - name: Regenerate APIs
-        run: scripts/generate_api.sh
-      - name: Update browser versions in README
-        run: scripts/update_readme.sh
-      - name: Verify API is up to date
-        run: |
-          if [[ -n $(git status -s) ]]; then
-            echo "ERROR: generated interfaces/docs differ from the current sources:"
-            git diff
-            exit 1
-          fi
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      uses: microsoft/playwright-github-action@v1
+    - continue-on-error: true
+      name: Download drivers
+      run: scripts/download_driver_for_all_platforms.sh
+    - continue-on-error: true
+      name: Regenerate APIs
+      run: scripts/generate_api.sh
+    - continue-on-error: true
+      name: Update browser versions in README
+      run: scripts/update_readme.sh
+    - continue-on-error: true
+      name: Verify API is up to date
+      run: "if [[ -n $(git status -s) ]]; then\n  echo \"ERROR: generated interfaces/docs\
+        \ differ from the current sources:\"\n  git diff\n  exit 1\nfi\n"
+    timeout-minutes: 30
+name: Verify API
+on:
+  repository_dispatch:
+    types: trigger-ga___verify_api.yml
